### ISSUE TITLE
Balance out News on US News Channel

### ISSUE THREAD

**Issue by JonM313** [RiiConnect24/File-Maker#31]
Error Code 107006 has been happening way way way too much on US News Channel! It keeps coming back or just won’t fix! A way to balance out the News on the US News Channel would be greatly appreciated!

**Comment by KcrPL** [comment]
Looks like @larsenv have to do something with the size limit. Or it's just parsing issue.

**Comment by larsenv** [comment]
I’ll take a look.

**Comment by larsenv** [comment]
a46abd6adf1cfd86bee2632aa3ff67aa5675579c might help fix some images that are too large, which happens with portrait pictures (usually used in sports news).

I'll keep the scripts running using this check I made for a bit, and hopefully it should make it better.

**Comment by KcrPL** [comment]
Nice! :)

**Comment by larsenv** [comment]
This issue shouldn't be closed, I said I'm gonna keep this running to see if 107006 happens less.

**Comment by KcrPL** [comment]
Oh, yeah. lmao
Hopefully it will.

**Comment by larsenv** [comment]
Pushed another fix - 73e4ae139cede65470cdc8231ed41f9b763128ae.

If an article is to appear twice in a news file (let's say it appears in National News and Business), make it only appear once in one category. I haven't done this before because I wanted it to appear in multiple categories at once if they are in multiple categories, but it could make it cleaner for places like the Globe.

This might be a temporary fix until I got something better.

@KcrPL Please don't close the PR yet until I am sure this makes the filesize smaller, or else I'm gonna go crazy.

**Comment by larsenv** [comment]
It's been a couple days and the filesize of the news files has shrunk a bit, so I'm gonna close this.
