### ISSUE TITLE
Sun icon for entire day in several cities

### ISSUE THREAD

**Issue by HilbertIdeals5** [RiiConnect24/File-Maker#52]
Short Description of Issue: 
Several cities on the Globe show the sun icon during the 12am-6am and 6pm-12pm sections.

Long Issue: 
The short description, plus this: I assume it's probably happening because the "Cold" condition uses the sun icon, but doesn't have day/night versions (as it says [here](https://developer.accuweather.com/weather-icons)). I first noticed this while checking several Southern cities during the snowstorm...
![Screen Shot 2021-02-15 at 2 40 53 PM](https://user-images.githubusercontent.com/63978875/109306525-499f0b80-780d-11eb-88b7-c0489be5eee9.png)
...and I also found this in other northern locations several days afterward.
![Screen Shot 2021-02-17 at 4 22 48 PM](https://user-images.githubusercontent.com/63978875/109306657-76532300-780d-11eb-99f2-5224c6c3540b.png)
<img width="1440" alt="Screen Shot 2021-02-22 at 10 44 48 AM" src="https://user-images.githubusercontent.com/63978875/109306661-794e1380-780d-11eb-9242-e57cb3c0ad97.png">

Steps to Reproduce :
- Go to the Wii Menu, and start the Forecast Channel.
- Check the globe, browse around for any cities where the weather is "Cold", or might be cold.
- When clicking on the Today/Tomorrow icon, there might be a sun in the 1st or 4th quarters.

**Comment by HilbertIdeals5** [comment]
It's been 3 weeks 😧

**Comment by larsenv** [comment]
I apologize for not responding. This was overlooked. Is this issue still happening?

Btw, if you can, it would be nice if you could talk to me on Discord about these issues instead of GitHub issues. It's easier than talking about the issues here, and most of the RC24 community is on Discord.

You can find me and others at https://discord.gg/rc24

**Comment by HilbertIdeals5** [comment]
OK then 👍🏼 Also, recently I couldn't find any cities with the same problem, but there were some in February.

**Comment by HilbertIdeals5** [comment]
The bug's come up again!

This is for the South Pole, right now:
![HAFE01_2021-06-13_18-36-22](https://user-images.githubusercontent.com/63978875/121823952-943a7b80-cc76-11eb-84ed-7d571d20f333.png)

It might have something to do with the fact that the weather is "Cold":
![HAFE01_2021-06-13_18-36-26](https://user-images.githubusercontent.com/63978875/121823959-9997c600-cc76-11eb-9412-29a6d415fe95.png)

This might also be the case for the "Hot" condition as well, so

**Comment by larsenv** [comment]
Is this really a bug?

We use the sun icon for "Hot" and "Cold" because the Forecast Channel does not have a more appropriate weather icon. Even when it's night. Thus, if it's hot or cold for 24 hours for some reason, the hourly forecast will be all sun.

There was an issue that I discovered where the hourly forecast was mostly wrong a few months ago, but I fixed that (you might have told me about it). We've been using AccuWeather's enterprise API since December which allows viewing of 6-hour forecasts.

**Comment by HilbertIdeals5** [comment]
The previous one was probably the one where the forecast was shifted forward 6 hours. For this, if it's not a bug, then it's more of an appearance thing, because having the sun icon when it's nighttime looks like a mistaken forecast.
