### ISSUE TITLE
Duplicate Kansas City's

### ISSUE THREAD

**Issue by HilbertIdeals5** [RiiConnect24/File-Maker#53]
Short Description of Issue: 
There are two Kansas City's.

Long Issue: 
https://user-images.githubusercontent.com/63978875/109402282-a93b0b00-7922-11eb-84ae-9eee43b33c26.mov

Steps to Reproduce :
- Go to the Wii Menu, and start the Forecast Channel.
- Go to the Globe.
- Find Kansas City, and zoom in all the way to be able to point at both of them.

**Comment by larsenv** [comment]
Actually, this is normal. Kansas City is a city in both Kansas and Missouri, believe it or not. It is separated by the state border. Nintendo included both of these cities. Because they are so close to each other, it's very likely that the weather data will be the same for both cities.

https://en.wikipedia.org/wiki/Kansas_City,_Missouri
https://en.wikipedia.org/wiki/Kansas_City,_Kansas

**Comment by HilbertIdeals5** [comment]
I just realized this got closed XD
Nice fact to know.
